# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0.0'

gem 'json', '~> 2.6'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-performance', '~> 1.16'
  gem 'rubocop-rspec', '~> 2.20'
  gem 'simplecov', '~> 0.22'
end

group :test do
  gem 'rspec-json_expectations', '~> 2.2'
end
